---
title: "sdm_plots_ggplot"
author: "Leonardo Feitosa"
date: "28/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(janitor)
library(raster)
library(patchwork)
library(rnaturalearth)
library(MetBrewer)
```

```{r}
# Set directories
basedir <- "G:/Meu Drive/S. tudes/data/"
rasterdir <- file.path(basedir, "raster_layers") # calls raster layers
presdir <- file.path(basedir, "present") # calls present data from raster files
futdir <- file.path(basedir, "future") # calls future data from raster files
outdir <- file.path(basedir, "outputs") # sends plots to the output folder
occurdir <- file.path(basedir, "occurrences") # calls the occurrence data
vardir <- file.path(basedir, "variables") # calls socioeconomic and fisheries variables
shapedir <- file.path(basedir, "shape_files") # calls the shapefiles
resultdir <- file.path("results")
```

```{r}
# test
df_orig <- raster::raster(file.path(presdir, "Present.Benthic.Mean.Depth.Dissolved.oxygen.Mean.tif")) 
```


```{r}
## Read in the data from the test models for variable importance
vars <- list.files(file.path(outdir, "auc"),
                   pattern = ".csv",
                   full.names = TRUE)

tbl <- sapply(vars, read.delim, simplify = FALSE, sep = ",")

vars_tbl <- tbl %>%
  bind_rows() 

#### Wrangling the data to create a long table
vars_long <- vars_tbl %>% 
  pivot_longer(cols = bioclim:maxent,
               names_to = "algorithm",
               values_to = "auc")

## Read in the data from final model
model_final <- read_csv(file.path(outdir, "auc_present.csv")) %>% 
  pivot_longer(cols = bioclim:maxent,
               names_to = "algorithm",
               values_to = "auc") %>% 
  mutate(variable = "full_model") %>% 
  relocate(variable, .before = algorithm)
```

```{r}
## Compute summary stats
vars_summary <- vars_long %>% 
  group_by(variable, algorithm) %>% 
  summarise(mean_auc = mean(auc),
            sd_auc = sd(auc))

## Summary stats of final model
final_summary <- model_final %>% 
  group_by(variable, algorithm) %>% 
  summarise(mean_auc = mean(auc),
            sd_auc = sd(auc))

summary_df <- full_join(vars_summary, final_summary, by = c("variable", "algorithm", "mean_auc", "sd_auc")) 


summary_df_wide <- vars_summary %>% 
  pivot_wider(names_from = starts_with(c("algorithm")),
              values_from = ends_with(c("auc"))) %>% 
  relocate(sd_auc_bioclim, .after = mean_auc_bioclim) %>% 
  relocate(sd_auc_gower, .after = mean_auc_gower) %>% 
  relocate(sd_auc_maha, .after = mean_auc_maha) %>% 
  relocate(sd_auc_maxent, .after = mean_auc_maxent)

#write_csv(summary_df_wide, path = here::here("data", "outputs", "tests_present", "summary_stats_tests.csv"), col_names = T)
```

```{r, fig.width=7, fig.height=4.5}
var_bold <- ifelse(levels(vars_summary$variable) == "Result", "bold", "plain")

vars_summary %>% 
    mutate(variable = case_when(
    variable == "surf_temperature" ~ "Surface Temperature (range)",
    variable == "surf_salinity" ~ "Surface Salinity (mean)",
    variable == "surf_do" ~ "Surface Dissolved Oxygen (range)",
    variable == "surf_productivity" ~ "Surface Primary Productivity (mean)",
    variable == "surf_ph" ~ "Surface pH (mean)",
    variable == "bent_light" ~ "Benthic light at bottom (range)",
    variable == "bent_productivity" ~ "Benthic Primary Productivity (mean)",
    variable == "full_model" ~ "Result",
    variable == "bent_do" ~ "Benthic Dissolved Oxygen (mean)",
    variable == "bent_salinity" ~ "Benthic Salinity (mean)",
    variable == "bent_curr_velocity" ~ "Benthic Current Velocity (mean)"
  )) %>% 
  mutate(algorithm = str_to_sentence(algorithm)) %>% 
  mutate(algorithm = case_when(
    algorithm == "Maha" ~ "Mahalanobis",
    algorithm == "Gower" ~ "DOMAIN",
    TRUE ~ algorithm
  )) %>% 
ggplot() +
  geom_point(aes(x = fct_rev(fct_relevel(variable,
                             labels = c("Result",
                                "Benthic Current Velocity (mean)",
                                "Benthic Dissolved Oxygen (mean)",
                                "Benthic light at bottom (range)",
                                "Benthic Primary Productivity (mean)",
                                "Benthic Salinity (mean)",
                                "Surface Dissolved Oxygen (range)",
                                "Surface pH (mean)",
                                "Surface Primary Productivity (mean)",
                                "Surface Salinity (mean)",
                                "Surface Temperature (range)"))), y = mean_auc, color = algorithm),
             show.legend = F,
             size = 2) +
  geom_linerange(aes(x = variable, ymin = mean_auc - sd_auc, ymax = mean_auc + sd_auc, color = algorithm),
                size = 0.6,
                show.legend = F) +
  geom_hline(yintercept = 0.7, color = "black", linetype = "dashed") +
  facet_wrap(~ algorithm, nrow = 1) +
  labs(x = "",
       y = "Mean AUC") +
  scale_color_manual(values = met.brewer("Java", 4)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, color = "black"),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(fill = "transparent"),
        strip.text = element_text(color = "black", size = 12),
        panel.spacing.x = unit(2, "mm"))


ggsave(file.path(outdir, "variable_test2.png"), width = 7, height = 4.5, dpi = 300)
```


```{r, fig.width=8}
ggplot(data = vars_summary %>% filter(algorithm == "bioclim")) +
  geom_point(aes(x = variable, y = mean_auc, color = algorithm),
             show.legend = F) +
  geom_errorbar(aes(x = variable, ymin = mean_auc - sd_auc, ymax = mean_auc + sd_auc)) +
  geom_hline(yintercept = 0.8204545) +
  scale_y_continuous(breaks = seq(0.6, 1, by = 0.1)) +
  labs(x = "",
       y = "Mean AUC",
       title = "Bioclim") +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

ggplot(data = vars_summary %>% filter(algorithm == "maha")) +
  geom_point(aes(x = variable, y = mean_auc, color = algorithm),
             show.legend = F) +
  geom_errorbar(aes(x = variable, ymin = mean_auc - sd_auc, ymax = mean_auc + sd_auc)) +
  geom_hline(yintercept = 0.9917355) +
  labs(x = "",
       y = "Mean AUC",
       title = "Mahalanobis") +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_text(size = 12, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

ggplot(data = vars_summary %>% filter(algorithm == "gower")) +
  geom_point(aes(x = variable, y = mean_auc, color = algorithm),
             show.legend = F) +
  geom_errorbar(aes(x = variable, ymin = mean_auc - sd_auc, ymax = mean_auc + sd_auc)) +
  geom_hline(yintercept = 0.9528926) +
  labs(x = "",
       y = "Mean AUC",
       title = "Gower") +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.text.x = element_blank())

ggplot(data = vars_summary %>% filter(algorithm == "maxent")) +
  geom_point(aes(x = variable, y = mean_auc, color = algorithm),
             show.legend = F) +
  geom_errorbar(aes(x = variable, ymin = mean_auc - sd_auc, ymax = mean_auc + sd_auc)) +
  geom_hline(yintercept = 0.9896694) +
  labs(x = "",
       y = "Mean AUC",
       title = "Maxent") +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.title.x = element_blank())
```


## Read back in the rasters written above

```{r}
# ocor dataset
ocor <- read.csv(file.path(occurdir, "occurrence_data.csv"), sep = ";") %>% 
  dplyr::select(long, lat)
# Binary map
#stud_bin_future <- raster::raster(file.path(futdir, "ensemble_stud_binary_future.tif"))
# Probabilty map
#stud_prob_future <- raster::raster(file.path(futdir, "ensemble_stud_prob_future.tif"))

# Binary map
#stud_bin_pres_comp <- raster::raster(file.path(presdir, "ensemble_stud_binary_present_comparison.tif"))
# Probabilty map
#stud_prob_pres_comp <- raster::raster(file.path(presdir, "ensemble_stud_prob_present_comparison.tif"))

# Binary map
stud_bin_pres <- raster::raster(file.path(outdir, "ensemble_stud_binary_present_comparison2.tif"))
# Probabilty map
stud_prob_pres <- raster::raster(file.path(outdir, "ensemble_stud_prob_present_comparison2.tif"))

# load shape files
## world countries
world <- ne_countries(scale = "medium", returnclass = "sf")
#read_sf(here::here("data", "shape_files", "world_countries", "World_Countries.shp"))
# Sphyrna tudes IUCN distribution map 
stud_dist_IUCN <- read_sf(file.path(shapedir, "stud", "data_0.shp")) %>%  
  clean_names() %>% 
  mutate(legend = case_when(
    str_detect(legend, "Extant") ~ "Extant"
  ))

#mangrove <- read_sf(file.path(shapedir, "mangroves", "GMW_2016_v2.shp"))
# Bathymetry layers
#bathy_0 <- read_sf(file.path(shapedir, "ne_10m_bathymetry_L_0.shp"))
bathy_200<-read_sf(file.path(shapedir, "bathymetry", "ne_10m_bathymetry_K_200.shp"))
# bathy_1k <-read_sf(file.path(shapedir, "ne_10m_bathymetry_J_1000.shp"))
# bathy_2k <-read_sf(file.path(shapedir, "ne_10m_bathymetry_I_2000.shp"))
# bathy_3k <-read_sf(file.path(shapedir, "ne_10m_bathymetry_H_3000.shp"))
# bathy_4k <-read_sf(file.path(shapedir, "ne_10m_bathymetry_G_4000.shp"))
# bathy_5k <-read_sf(file.path(shapedir, "ne_10m_bathymetry_F_5000.shp"))
```

```{r}
# Check the CRS for the world and stud_dist_IUCN shape files
world %>% st_crs() # WGS 84, CRS = 4326
stud_dist_IUCN %>% st_crs() # WGS 84, CRS = 4326
```


```{r}
# Create df from rasters
# stud_bin_fut_df <- raster::rasterToPoints(stud_bin_future) %>% 
#   as.data.frame() %>% 
#   rename(ensemble = ensemble_stud_binary_future)
# 
# stud_prob_fut_df <- raster::rasterToPoints(stud_prob_future) %>% 
#   as.data.frame() %>% 
#   rename(ensemble = ensemble_stud_prob_future)
# 
# stud_bin_pres_comp_df <- raster::rasterToPoints(stud_bin_pres_comp) %>% 
#   as.data.frame() %>% 
#   rename(ensemble = ensemble_stud_binary_present_comparison)
# 
# stud_prob_pres_comp_df <- raster::rasterToPoints(stud_prob_pres_comp) %>% 
#   as.data.frame() %>%  
#   rename(ensemble = ensemble_stud_prob_present_comparison)

stud_bin_pres_df <- raster::rasterToPoints(stud_bin_pres) %>% 
  as.data.frame()  %>% 
  rename(ensemble = ensemble_stud_binary_present_comparison2)

#write_csv(stud_bin_pres_df, file = file.path(outdir, "binary_ensemble_df.csv"), col_names = T)

stud_prob_pres_df <- raster::rasterToPoints(stud_prob_pres) %>% 
  as.data.frame() %>% 
  rename(ensemble = ensemble_stud_prob_present_comparison2)

#write_csv(stud_prob_pres_df, file = file.path(outdir, "probability_ensemble_df.csv"), col_names = T)
```

```{r, fig.width=9, fig.height=10}
# WORK ON TRYING TO PLOT THE S. TUDES DISTRIBUTION MAP FROM IUCN
ggplot() +
  geom_sf(data = world) +
 geom_sf(data = stud_dist_IUCN,
         aes(fill = legend)) +
  coord_sf(xlim = c(-108, -25),
           ylim = c(-60, 50),
           expand = FALSE) +
  theme_bw()
```

```{r code for plotting a map with bathymetry data}
  # geom_sf(data = bathy_0,
  #         aes(fill = depth)) +
  # geom_sf(data = bathy_200,
  #         aes(fill = depth,
  #             color = depth),
  #         show.legend = F) +
  # geom_sf(data = bathy_1k,
  #         aes(fill = depth,
  #             color = depth),
  #         show.legend = F) +
  # geom_sf(data = bathy_2k,
  #         aes(fill = depth,
  #             color = depth),
  #         show.legend = F) +
  # geom_sf(data = bathy_3k,
  #         aes(fill = depth,
  #             color = depth),
  #         show.legend = F) +
  # geom_sf(data = bathy_5k,
  #         aes(fill = depth,
  #             color = depth),
  #         show.legend = F) +
  # scale_color_gradient(low = "steelblue1", high = "royalblue4",
  #                     breaks = seq(200, 5000, by = 2400),
  #                     labels = c("<200", "2600", "5000")) +
```

```{r}
bathy_200_geo <- bathy_200 %>% 
  st_drop_geometry()

mangrove_drop <- mangrove %>% 
  st_drop_geometry( )
```


```{r}
ggplot(data = bathy_200 %>% ) +
  geom_sf(fill = NA) +
  coord_sf(xlim = c(-120, -20),
           ylim = c(-60, 50),
           expand = FALSE)
```


## Trying to plot rasters in ggplot
future_comp_bin <- 
```{r, fig.height=9, fig.width=9}
# future_comp_bin <- ggplot() +
#   geom_raster(data = stud_bin_fut_df,
#               aes(x = x, y = y, fill = ensemble)) +
#   geom_sf(data = world,
#           color = "black") +
#   geom_sf(data = bathy_200, fill = NA) +
#   scale_fill_gradient2(breaks = seq(0, 1, by = 1),
#                        labels = c("None", "High")) +
#   geom_point(data = ocor, 
#              aes(x = long, y = lat),
#              pch = 21,
#              fill = "maroon2",
#              color = "black",
#              alpha = 0.8,
#              size = 1.3) +
#   coord_sf(xlim = c(-120, -20),
#            ylim = c(-60, 50),
#            expand = FALSE) +
#   labs(x = "",
#        y = "",
#        fill = "Suitability",
#        title = "Binary map S. tudes Future prediction RCP 4.5") +
#   theme_bw() +
#   theme(axis.text = element_text(color = "black", size = 11))
```

```{r, fig.height=9, fig.width=9}
# pres_com_bin <- ggplot() +
#   geom_raster(data = stud_bin_pres_comp_df,
#               aes(x = x, y = y, fill = ensemble),
#               show.legend = F) +
#   geom_sf(data = world,
#           color = "black") +
#   geom_sf(data = bathy_200, fill = NA) +
# 
#   scale_fill_gradient2() +
#   geom_point(data = ocor, 
#              aes(x = long, y = lat),
#              pch = 21,
#              fill = "maroon2",
#              color = "black",
#              alpha = 0.8,
#              size = 1.3) +
#   coord_sf(xlim = c(-120, -20),
#            ylim = c(-60, 50),
#            expand = FALSE) +
#   labs(x = "",
#        y = "",
#        title = "Binary map S. tudes present") +
#   theme_bw() +
#   theme(axis.text = element_text(color = "black", size = 11))
```


```{r, fig.height=9, fig.width=9}
# future_comp <-
#   ggplot() +
#   geom_raster(data = stud_prob_fut_df, 
#             aes(x = x, y = y, fill = ensemble)) +
#   geom_sf(data = world) +
#   geom_sf(data = bathy_200, fill = NA,
#           color = "black") +
#   geom_point(data = ocor, 
#              aes(x = long, y = lat),
#              pch = 21,
#              fill = "maroon2",
#              color = "black",
#              alpha = 0.8,
#              size = 1.3) +
#   scale_fill_viridis_c(breaks = seq(0, 12, by = 12),
#                        labels = c("Low", "High")) +
#   coord_sf(xlim = c(-120, -20),
#            ylim = c(-60, 50),
#            expand = FALSE) +
#   labs(x = "",
#        y = "",
#        fill = "Suitability",
#        title = "Probability map S. tudes Future") +
#   theme_bw() +
#   theme(axis.text = element_text(color = "black", size = 11))
```

```{r, fig.height=9, fig.width=9}
# present_comp <- ggplot() +
#   geom_raster(data = stud_prob_pres_comp_df, 
#             aes(x = x, y = y, fill = ensemble),
#             show.legend = F) +
#   geom_sf(data = world) +
#   geom_sf(data = bathy_200, fill = NA,
#           color = "black") +
#   geom_point(data = ocor, 
#              aes(x = long, y = lat),
#              pch = 21,
#              fill = "maroon2",
#              color = "black",
#              alpha = 0.8,
#              size = 1.3) +
#   scale_fill_viridis_c() +
#   coord_sf(xlim = c(-120, -20),
#            ylim = c(-60, 50),
#            expand = FALSE) +
#   labs(x = "",
#        y = "",
#        title = "Probability map S. tudes present") +
#   theme_bw() +
#   theme(axis.text = element_text(color = "black", size = 11))
```

```{r, fig.height=11, fig.width=11}
# (pres_com_bin + future_comp_bin) /
#   (present_comp + future_comp) +
#   plot_layout(widths = c(3,3),
#               heights = c(3,3))
# 
# ggsave(here::here("data", "outputs", "composite_figures_for_present_and_future_maps_for_comparison.png"),
#        width = 11, height = 11, dpi = 300)
# 
# ggsave(here::here("data", "outputs", "composite_figures_for_present_and_future_maps_for_comparison.tiff"), 
#        width = 11, height = 11, compression = "lzw", dpi = 300)
```

```{r, fig.height=9, fig.width=9}
# future_comp_zoom <- 
#   ggplot() +
#   geom_raster(data = stud_prob_fut_df, 
#             aes(x = x, y = y, fill = ensemble)) +
#   geom_sf(data = world) +
#   geom_sf(data = bathy_200, fill = NA,
#           color = "black") +
#   geom_point(data = ocor, 
#              aes(x = long, y = lat),
#              pch = 21,
#              fill = "maroon2",
#              color = "black",
#              alpha = 0.8,
#              size = 2) +
#   scale_fill_viridis_c(breaks = seq(0, 12, by = 12),
#                        labels = c("Low", "High")) +
#   coord_sf(xlim = c(-80, -30),
#            ylim = c(-10, 20),
#            expand = FALSE) +
#   labs(x = "",
#        y = "",
#        title = "Probability map S. tudes Future",
#        fill = "Probability of occurrence") +
#   theme_bw() +
#   theme(axis.text = element_text(color = "black", size = 11))
```


```{r, fig.height=9, fig.width=9}
# pres_comp_zoom <- 
#   ggplot() +
#   geom_raster(data = stud_prob_pres_comp_df,
#               aes(x = x, y = y, fill = ensemble),
#             show.legend = F) +
#   geom_sf(data = world) +
#   geom_sf(data = bathy_200,
#           fill = NA,
#           color = "black") +
#   geom_point(data = ocor, 
#              aes(x = long, y = lat),
#              pch = 21,
#              fill = "maroon2",
#              color = "black",
#              alpha = 0.8,
#              size = 2) +
#   scale_fill_viridis_c() +
#   coord_sf(xlim = c(-80, -30),
#            ylim = c(-10, 20),
#            expand = FALSE) +
#   labs(x = "",
#        y = "",
#        title = "Probability map S. tudes present",
#        fill = "Probability of occurrence") +
#   theme_bw() +
#   theme(axis.text = element_text(color = "black", size = 11))
```


```{r, fig.height=9, fig.width=9}
# pres_comp_zoom / 
#   future_comp_zoom
# 
# ggsave(here::here("data", "outputs", "composite_figures_for_suitability_pres_and_future_zoom.png"),
#        width = 11, height = 11, dpi = 300)
# 
# ggsave(here::here("data", "outputs", "composite_figures_for_suitability_pres_and_future_zoom.tiff"), 
#        width = 10, height = 10, compression = "lzw", dpi = 300)
```

```{r}
iucn_stud <- 
  ggplot() +
  geom_sf(data = world,
          size = 0.5) +
  geom_sf(data = stud_dist_IUCN,
          aes(fill = legend,
              color = legend)) +
  geom_text() +
  annotate("text", label = "A",
           x = -104, y = 46, size = 5, color = "black") +
  coord_sf(xlim = c(-108, -25),
           ylim = c(-60, 50),
           expand = FALSE) +
  scale_fill_manual(values = "#D55E00",
                    labels = c("Extant")) +
  scale_color_manual(values = "#D55E00",
                    labels = c("Extant")) +
  labs(x = "",
       y = "",
       fill = "",
       color = "") +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.key = element_rect(color = "black", size = .5),
        legend.position = c(.15, .2),
        panel.grid = element_blank(), 
        legend.background = element_rect(fill = "transparent")) 
```


```{r, fig.length = 10, fig.height=10}
bin_pres <-
  ggplot() +
  geom_raster(data = stud_bin_pres_df,
              aes(x = x, y = y, fill = factor(ensemble))) +
  geom_sf(data = world) +
  # geom_sf(data = bathy_200,
  #         fill = NA,
  #         color = "black") +
   geom_point(data = ocor, 
             aes(x = long, y = lat),
             pch = 21,
             fill = "maroon2",
             color = "black",
             alpha = 0.5,
             size = 1.5) +
    geom_text() +
  annotate("text", label = "B",
           x = -104, y = 46, size = 5, color = "black") +
  scale_fill_manual(values = c("white", "#005AB5", "green"),
                    labels = c("Not suitable", "Suitable", "Extant (IUCN)")) +
  coord_sf(xlim = c(-108, -25),
           ylim = c(-60, 50),
           expand = FALSE) +
  labs(x = "",
       y = "",
       fill = "") +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.key = element_rect(color = "black", size = 1),
        legend.position = c(.2, .2),
        legend.background = element_rect(fill = "transparent"))
```


```{r, fig.height=9, fig.width=9}
iucn_stud + bin_pres +
  plot_layout(widths = c(1,1))

ggsave(file.path(outdir, "composite_of_present_models_with_all_vars_new_model.png"),
       width = 11, height = 9, dpi = 300)

#ggsave(here::here("data", "outputs", "composite_of_present_models_with_all_vars.tiff"), width = 10, height = 10, compression = "lzw", dpi = 300)
```



```{r}
# prob_pres_zoom_north <- 
#   ggplot() +
#   geom_sf(data = world) +
#   geom_raster(data = stud_prob_pres_df, 
#             aes(x = x, y = y, fill = ensemble)) +
#   geom_point(data = ocor, 
#              aes(x = long, y = lat),
#              pch = 21,
#              fill = "maroon2",
#              color = "black",
#              alpha = 0.5,
#              size = 2) +
#   scale_fill_viridis_c(breaks = seq(0, 18, by = 17),
#                        labels = c("Low", "High")) +
#   coord_sf(xlim = c(-100, -70),
#            ylim = c(15, 40),
#            expand = FALSE) +
#   labs(x = "",
#        y = "",
#        fill = "Suitability") +
#   theme_bw() +
#   theme(axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         legend.position = c(.15, .8),
#         legend.background = element_rect(fill = "transparent"),
#         legend.text = element_text(color = "black"),
#         legend.title = element_text(color = "black")) +
#   guides(fill = guide_colorbar(ticks = F,
#                                barwidth = 0.8))
```

```{r}
prob_pres_zoom_center <- 
  ggplot() +
  geom_sf(data = world) +
  geom_raster(data = stud_prob_pres_df, 
            aes(x = x, y = y, fill = ensemble),
            show.legend = F) +
  geom_point(data = ocor, 
             aes(x = long, y = lat),
             pch = 21,
             fill = "maroon2",
             color = "black",
             alpha = 0.5,
             size = 2) +
  geom_text() +
  annotate("text", label = "B",
           x = -32, y = 18, size = 5, color = "white") +
  scale_fill_viridis_c(breaks = seq(0, 18, by = 17),
                       labels = c("0%", "100%")) +
  coord_sf(xlim = c(-78, -30),
           ylim = c(-10, 20),
           expand = FALSE) +
  labs(x = "",
       y = "",
       fill = "Suitability") +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(.9, .75),
        legend.background = element_rect(fill = "transparent"),
        legend.text = element_text(color = "white"),
        legend.title = element_text(color = "white")) +
  guides(fill = guide_colorbar(ticks = F,
                               barwidth = 0.8))
```

```{r}
prob_pres_zoom_south <-
  ggplot() +
  geom_sf(data = world) +
  geom_raster(data = stud_prob_pres_df, 
            aes(x = x, y = y, fill = ensemble),
            show.legend = F) +
  geom_point(data = ocor, 
             aes(x = long, y = lat),
             pch = 21,
             fill = "maroon2",
             color = "black",
             alpha = 0.5,
             size = 2.5) +
  geom_text() +
  annotate("text", label = "C",
           x = -58.4, y = -11, size = 5, color = "black") +
  scale_fill_viridis_c(breaks = seq(0, 18, by = 16),
                       labels = c("0%", "100%")) +
  coord_sf(xlim = c(-60, -30),
           ylim = c(-40, -10),
           expand = FALSE) +
  labs(x = "",
       y = "",
       fill = "Suitability") +
  theme_void() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(.15, .2),
        legend.background = element_rect(fill = "transparent"),
        legend.text = element_text(color = "black"),
        legend.title = element_text(color = "black"),
        axis.line = element_line(color = "black"),
        axis.line.y.right = element_line(color = "black"),
        plot.background = element_blank()) +
  guides(fill = guide_colorbar(ticks = F,
                               barwidth = 0.8))
```

```{r, fig.width=10, fig.height=10}
prob_pres <- 
  ggplot() +
  geom_raster(data = stud_prob_pres_df, 
            aes(x = x, y = y, fill = ensemble)) +
  geom_sf(data = world) +
  # geom_sf(data = bathy_200, fill = NA,
  #         color = "black") +
  geom_point(data = ocor, 
             aes(x = long, y = lat),
             pch = 21,
             fill = "maroon2",
             color = "black",
             alpha = 0.5,
             size = 1.5) +
  geom_text() +
  annotate("text", label = "A",
           x = -104, y = 46, size = 5, color = "black") +
  scale_fill_viridis_c(breaks = seq(0, 18, by = 16),
                       labels = c("0%", "100%")) +
  coord_sf(xlim = c(-108, -25),
           ylim = c(-60, 50),
           expand = FALSE) +
   geom_polygon(data = data.frame("x" = c(-78, -78,
                                          -30, -30), 
                                  "y" = c(-9.9, 20, 
                                          20, -9.9)),
                mapping = aes(x = x, y = y), 
                fill = NA,
                color = "black",
                size = .7) +
   geom_polygon(data = data.frame("x" = c(-60, -60,
                                          -30, -30), 
                                  "y" = c(-40, -10, 
                                          -10, -40)),
                mapping = aes(x = x, y = y), 
                fill = NA,
                color = "black",
                size = .7) +
  labs(x = "",
       y = "",
       fill = "Suitability") +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(.15, .2),
        legend.background = element_rect(fill = "transparent"),
        legend.text = element_text(color = "white"),
        legend.title = element_text(color = "white")) +
  guides(fill = guide_colourbar(ticks = F,
                                barwidth = 0.8))

# ggsave(file.path(outdir, "probability_map_with_all_vars_new_model.png"),
#        width = 11, height = 9, dpi = 300)
```

```{r, fig.height=9, fig.width=11}
arrow_a <- data.frame(x1 = 13, x2 = 15.6, y1 = 11, y2 = 12.5)
arrow_b <- data.frame(x1 = 12.68, x2 = 18, y1 = 8.5, y2 = 7.5)

ggplot() +
  coord_equal(xlim = c(0,30), ylim = c(0,20), expand = FALSE) +
  annotation_custom(ggplotGrob(prob_pres),
                    xmin = 0, xmax = 14.5, ymin = 0, ymax = 20) +
  annotation_custom(ggplotGrob(prob_pres_zoom_center),
                    xmin = 15, xmax = 30, ymin = 10, ymax = 19.5) +
  annotation_custom(ggplotGrob(prob_pres_zoom_south),
                    xmin = 19.25, xmax = 30, ymin = 0, ymax = 10.8) +
  geom_segment(data = arrow_a, aes(x = x1, y = y1, xend = x2, yend = y2),
               arrow = arrow(), lineend = "round", size = .6) +
  geom_segment(data = arrow_b, aes(x = x1, y = y1, xend = x2, yend = y2),
               arrow = arrow(), lineend = "round", size = .6) +
  theme_void()

ggsave(file.path(outdir, "composite_of_probability_with_all_vars_new_model_2.png"),
       width = 11, height = 9, dpi = 300)
```




































